//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberStudentGroup.ADO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Please the groups title.")]
        [Display(Name = "Group Title")]
        public string Title { get; set; }


        [Required(ErrorMessage = "Please the groups Description.")]
        [Display(Name = "Group Description")]
        public string Desc { get; set; }


        [Required]
        [Display(Name = "Author")]
        public int AuthorId { get; set; }


    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
