//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberStudentGroup.ADO
{
    using System;
    using System.Collections.Generic;
    using System.Web.DynamicData;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;

    public partial class Message
    {
        public int Id { get; set; }
        public int ChatId { get; set; }
        public int UserId { get; set; }
        public string SentDate { get; set; }
        public string Text { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual User User { get; set; }
    }
}
